### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by antoineco**

### CODE REVIEW

**Comment by antoineco** [comment]
@sameersbn I opened this PR so we can merge an old branch (and close #53), but CircleCI seems to run against the branch, not the _merge_ of the branch onto the target.

Is there any way to change that?

**Comment by sameersbn** [comment]
@antoineco I think you can rebase the `mrhinkle-patch-1` branch. As the branch exists on this repo, you should have the privileges to do that.

**Comment by antoineco** [comment]
@sameersbn for this one sure, I can do that. I was just taking the situation as an example because eventually we're gonna want to prevent issues introduced by a merge before they make it to the target branch. Tests can pass on the branch, but it's even more important to test the _merged_ branch.

**Comment by sameersbn** [comment]
@antoineco Sorry for the misunderstanding.

From what I can tell circleci does not have a builtin option to test a merge before the actual merge. The orb https://github.com/NarrativeScience/circleci-orb-ghpr can be used though I am not sure if it will carry out the merge automatically if it's a success.

I have used https://github.com/apps/bors for this in the past. It's a bot that will test a merge (or a batch of merges) and automatically merge the PR's if all the tests pass on a merged commit. 

The workflow with bors is :
 1. CI tests pass
 2. Reviewers approve the PR and comment with `bors merge`
 3. Bors will batch all approved pull requests, run the tests again and merge all the PR's on success

The bummer is bors does not support private repos.

**Comment by antoineco** [comment]
Looks like `ghpr` could do the trick. To me it's not important to have a merge bot, just something that merges the branch locally before executing tests, and reports failure or success.

I was really surprised to read CircleCI doesn't have such feature. I think we both checked https://ideas.circleci.com/ideas/CCI-I-926 :wink:

**Pull request merged**
