### PR TITLE
Rename repo to aws-event-sources

### LINKED ISSUE #56: Discuss renaming project to aws-event-sources
Since the events are not really being used for AWS lambdas.

### PR DESCRIPTION
**Pull request by antoineco**
Closes #56

### CODE REVIEW

**Comment by sameersbn** [comment]
@antoineco mostly lgtm, the `working_directory` path in `.circleci/config.yml` file needs to be updated for completeness. 

But I am not able to understand why the CI did not pick up this PR

**Comment by sameersbn** [comment]
Ah the CI is configured to not build PR's from forked repos

**Comment by antoineco** [comment]
Thanks for the pointer! I'll add that change.

Should I submit the PR again from the original repo?

**Comment by sameersbn** [comment]
> Should I submit the PR again from the original repo?

It's okay. I have changed the configuration on circleci

**Comment by antoineco** [comment]
@sameersbn [done](https://github.com/triggermesh/aws-event-sources/compare/71d5fe716303eef2f0263809ca9cc1b4d3dd69f8..9015265f973c79e147a6090c926c3cac35cd2925)

**Pull request merged**
