### PR TITLE
Reorganize reconciler packages and add unit tests

### LINKED ISSUE #91: Add unit tests for reconcilers

### PR DESCRIPTION
**Pull request by antoineco**
1. Common helpers have been moved to `common` sub-packages, and a `testing` package was created with utilities that can be imported in tests.
2. There is now a single `AWSEventSourceStatus` struct common to all event sources, since they all expose the same status conditions.
3. All packages are covered to a least 90%, reconciliation tests leverage Knative's Table tests.

```
pkg/reconciler
├── awscodecommitsource
├── awscognitosource
├── awsdynamodbsource
├── awsiotsource
├── awskinesissource
├── awssnssource
├── awssqssource
├── common
│   ├── event
│   ├── object
│   ├── resource
│   └── semantic
└── testing
```

Closes #91

### CODE REVIEW

**Comment by antoineco** [comment]
@sameersbn the CI fails with `bad output from test2json`, are you familiar with that error?

**Comment by sameersbn** [comment]
> @sameersbn the CI fails with `bad output from test2json`, are you familiar with that error?

Haven't seen it before. Are you able to run the tests on your machine with `go test` and `gotestsum`?
Maybe this has some clues https://github.com/golang/go/issues/27582

**Comment by antoineco** [comment]
Both are running alright locally:
```
gotestsum --junitfile aws-event-sources-unit-tests.xml -- -cover -coverprofile=c.out ./pkg/adapter/... ./pkg/apis/... ./pkg/reconciler/...
✓  pkg/adapter/awssqssource (43ms) (coverage: 42.6% of statements)
✓  pkg/adapter/awsdynamodbsource (37ms) (coverage: 63.3% of statements)
✓  pkg/adapter/awssnssource (45ms) (coverage: 67.3% of statements)
✓  pkg/adapter/awscognitosource (60ms) (coverage: 66.7% of statements)
✓  pkg/adapter/awskinesissource (133ms) (coverage: 66.7% of statements)
✓  pkg/adapter/awscodecommitsource (335ms) (coverage: 59.8% of statements)
∅  pkg/apis/sources
∅  pkg/apis/sources/v1alpha1
✓  pkg/reconciler/awscodecommitsource (1.115s) (coverage: 91.6% of statements)
✓  pkg/reconciler/awscognitosource (958ms) (coverage: 91.7% of statements)
✓  pkg/reconciler/common/object (92ms) (coverage: 100.0% of statements)
✓  pkg/reconciler/awsdynamodbsource (999ms) (coverage: 91.7% of statements)
✓  pkg/reconciler/awsiotsource (1.231s) (coverage: 91.2% of statements)
✓  pkg/reconciler/common/event (36ms) (coverage: 100.0% of statements)
✓  pkg/reconciler/common/semantic (47ms) (coverage: 77.8% of statements)
✓  pkg/reconciler/awssnssource (1.059s) (coverage: 91.2% of statements)
✓  pkg/reconciler/awskinesissource (1.219s) (coverage: 91.2% of statements)
✓  pkg/reconciler/awssqssource (1.029s) (coverage: 91.2% of statements)
∅  pkg/reconciler/common
✓  pkg/reconciler/common/resource (28ms) (coverage: 100.0% of statements)
∅  pkg/reconciler/testing
```

**Comment by sameersbn** [comment]
@antoineco I see the following lines in the logs 

```
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
 ``

Can you try add ing `-p=1` to the `test` target in `scripts/inc.Target` ? I think we could be running out of memory on the ci instance

**Comment by sameersbn** [comment]
the root Makefile also has `test` target, add it there as well

**Comment by sameersbn** [comment]
@antoineco I've created a PR against your branch to workaround this issue. It turns out that the `pkg` tests request more memory than the CI instance can provide. I've disabled parallelization of the `pkg` tests to workaround this issue.

**Comment by antoineco** [comment]
@sameersbn thanks for looking into it! I didn't have time yesterday. Should I cherry pick the commit from #121?

**Pull request merged**
