### PR TITLE
Merge reconciler/adapter feature branch

### PR DESCRIPTION
**Pull request by antoineco**
**Proposed changes**

* Adds a controller that can reconcile custom Source objects and register Event Types for all AWS event sources
* Refactor all AWS event sources to use Knative Eventing's adapter lib (except for AWS IoT which is written in Python)

This PR is just the aggregation of all previous individual PRs to the feature branch.

Useful docs:
* [DEVELOPMENT.md](https://github.com/triggermesh/aws-event-sources/blob/feature/reconciler-adapter/DEVELOPMENT.md)
* [awscodecommitsource/README.md](https://github.com/triggermesh/aws-event-sources/blob/feature/reconciler-adapter/cmd/awscodecommitsource/README.md)
* [awscognitosource/README.md](https://github.com/triggermesh/aws-event-sources/blob/feature/reconciler-adapter/cmd/awscognitosource/README.md)
* [awsdynamodbsource/README.md](https://github.com/triggermesh/aws-event-sources/blob/feature/reconciler-adapter/cmd/awsdynamodbsource/README.md)
* [awskinesissource/README.md](https://github.com/triggermesh/aws-event-sources/blob/feature/reconciler-adapter/cmd/awskinesissource/README.md)
* [awssnssource/README.md](https://github.com/triggermesh/aws-event-sources/blob/feature/reconciler-adapter/cmd/awssnssource/README.md)
* [awssqssource/README.md](https://github.com/triggermesh/aws-event-sources/blob/feature/reconciler-adapter/cmd/awssqssource/README.md)

### CODE REVIEW

**Comment by sebgoa** [comment]
Let's setup a demo to approve this merge.

**Comment by antoineco** [comment]
Rebased on `master` to fix a conflict caused by #97

**Comment by sameersbn** [comment]
@antoineco @sebgoa do you think we should squash this PR before the merge?

**Comment by antoineco** [comment]
We could have one commit for reconcilers, one for adapters, and one for CI suff. What do you think?

**Comment by sameersbn** [comment]
sgtm!

**Comment by sebgoa** [comment]
I would not squash everything, maybe what antoine says

**Comment by antoineco** [comment]
PR squashed into 4 logical commits.

**Pull request merged**
